// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need a DIRECT Postgres connection. On Neon the runtime
    // DATABASE_URL is the pooled (pgbouncer) endpoint, which `prisma migrate`
    // can't use — so when DIRECT_DATABASE_URL is set (production), migrations
    // use it instead. Locally only DATABASE_URL exists and is already direct.
    url: process.env["DIRECT_DATABASE_URL"] || process.env["DATABASE_URL"],
  },
});
